version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./api/api/.env

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: