version: '3.8'

networks:
  ecomm_network:

services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./api/api/.env
    volumes:
      - static_volume:/api/static
      - media_volume:/api/media
    networks:
      - ecomm_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - ecomm_network

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecomm_network

  nginx:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - backend
      - frontend
    networks:
      - ecomm_network

volumes:
  postgres_data:
  static_volume:
  media_volume:
