version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./api/api/.env
    volumes:
      - static_volume:/api/static
      - media_volume:/api/media

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - frontend_build:/frontend/build/dist

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/var/www/frontend
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  frontend_build:
  static_volume:
  media_volume:
