version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Test123!
      - POSTGRES_DB=BlueElf
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: