# Generated by Django 4.1.7 on 2023-05-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productminfo',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='productminfo',
            name='specs',
        ),
        migrations.AlterField(
            model_name='product',
            name='frequently_bought_with',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=120)),
                ('spec_info', models.CharField(max_length=200)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.productminfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductKeyAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_name', models.CharField(max_length=120)),
                ('att_stat', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_attributes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(max_length=300)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='products.productminfo')),
            ],
        ),
    ]
