# Generated by Django 4.1.7 on 2023-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productminfo_bullets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flat_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='perc_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
