# Generated by Django 4.1.7 on 2023-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_flat_discount_product_perc_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='insurance_base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance_daily_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
