# Generated by Django 4.1.7 on 2023-06-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_local_competitor_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='local_competitor_cost',
            new_name='local_competitor_daily_cost',
        ),
    ]
